package panzerWaltz;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static panzerWaltz.FlairImage.*;
import panzerWaltz.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.06 00:32:57 // Generated by ComTest
 *
 */
public class FlairImageTest {



  // Generated by ComTest BEGIN
  /** testFlairImage33 */
  @Test
  public void testFlairImage33() {    // FlairImage: 33
    FlairImage testi = new FlairImage(); 
    assertEquals("From: FlairImage line: 35", " 0", testi.toString()); 
    assertEquals("From: FlairImage line: 36", 0, testi.getNumber()); 
    assertEquals("From: FlairImage line: 37", "", testi.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSeparateNumber116 */
  @Test
  public void testSeparateNumber116() {    // FlairImage: 116
    java.util.concurrent.atomic.AtomicBoolean totuus = new java.util.concurrent.atomic.AtomicBoolean(false); 
    StringBuilder testi = new StringBuilder(); 
    assertEquals("From: FlairImage line: 120", 0, separateNumber(testi,'-',totuus)); 
    totuus.set(false); 
    testi = new StringBuilder("123-asdasd"); 
    assertEquals("From: FlairImage line: 124", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 125", "asdasd", testi.toString()); 
    assertEquals("From: FlairImage line: 126", true, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("123-asdasd-muumi"); 
    assertEquals("From: FlairImage line: 130", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 131", "asdasd-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 132", true, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-asdasd-muumi"); 
    assertEquals("From: FlairImage line: 136", 0, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 137", "asd-asdasd-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 138", false, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-asdasd-123"); 
    assertEquals("From: FlairImage line: 142", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 143", "asd-asdasd-123", testi.toString()); 
    assertEquals("From: FlairImage line: 144", false, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-123-muumi"); 
    assertEquals("From: FlairImage line: 148", 0, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 149", "asd-123-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 150", false, totuus.get()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTakeNumberFromString181 */
  @Test
  public void testTakeNumberFromString181() {    // FlairImage: 181
    assertEquals("From: FlairImage line: 182", 123, takeNumberFromString("123")); 
    assertEquals("From: FlairImage line: 183", 0, takeNumberFromString("123a")); 
    assertEquals("From: FlairImage line: 184", -123, takeNumberFromString("-123")); 
    assertEquals("From: FlairImage line: 185", 0, takeNumberFromString("--123")); 
    assertEquals("From: FlairImage line: 186", 0, takeNumberFromString("pz4")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testShorten203 */
  @Test
  public void testShorten203() {    // FlairImage: 203
    assertEquals("From: FlairImage line: 204", "", shorten("asd.asd",7)); 
    assertEquals("From: FlairImage line: 205", "C:/Users/", shorten("C:/Users/asd.asd",7)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTakeExtensionAway218 */
  @Test
  public void testTakeExtensionAway218() {    // FlairImage: 218
    assertEquals("From: FlairImage line: 219", "asd", takeExtensionAway("asd.asd")); 
    assertEquals("From: FlairImage line: 220", "asd", takeExtensionAway("asd.a")); 
    assertEquals("From: FlairImage line: 221", "asd", takeExtensionAway("asd.")); 
    assertEquals("From: FlairImage line: 222", "asd", takeExtensionAway("asd")); 
    assertEquals("From: FlairImage line: 223", "", takeExtensionAway(".asd")); 
    assertEquals("From: FlairImage line: 224", "", takeExtensionAway(".")); 
    assertEquals("From: FlairImage line: 225", "asd.asd", takeExtensionAway("asd.asd.asd")); 
    assertEquals("From: FlairImage line: 226", "merkki.jono", takeExtensionAway("merkki.jono.png")); 
    assertEquals("From: FlairImage line: 227", "mer.kki.jono", takeExtensionAway("mer.kki.jono.png")); 
  } // Generated by ComTest END
}