package panzerWaltz;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static panzerWaltz.FlairImage.*;
import panzerWaltz.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.26 19:42:38 // Generated by ComTest
 *
 */
public class FlairImageTest {



  // Generated by ComTest BEGIN
  /** testFlairImage33 */
  @Test
  public void testFlairImage33() {    // FlairImage: 33
    FlairImage testi = new FlairImage(); 
    assertEquals("From: FlairImage line: 35", "0|", testi.toString()); 
    assertEquals("From: FlairImage line: 36", 0, testi.getNumber()); 
    assertEquals("From: FlairImage line: 37", "", testi.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSeparateNumber131 */
  @Test
  public void testSeparateNumber131() {    // FlairImage: 131
    java.util.concurrent.atomic.AtomicBoolean totuus = new java.util.concurrent.atomic.AtomicBoolean(false); 
    StringBuilder testi = new StringBuilder(); 
    assertEquals("From: FlairImage line: 135", 0, separateNumber(testi,'-',totuus)); 
    totuus.set(false); 
    testi = new StringBuilder("123-asdasd"); 
    assertEquals("From: FlairImage line: 139", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 140", "asdasd", testi.toString()); 
    assertEquals("From: FlairImage line: 141", true, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("123-asdasd-muumi"); 
    assertEquals("From: FlairImage line: 145", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 146", "asdasd-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 147", true, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-asdasd-muumi"); 
    assertEquals("From: FlairImage line: 151", 0, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 152", "asd-asdasd-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 153", false, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-asdasd-123"); 
    assertEquals("From: FlairImage line: 157", 123, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 158", "asd-asdasd-123", testi.toString()); 
    assertEquals("From: FlairImage line: 159", false, totuus.get()); 
    totuus.set(false); 
    testi = new StringBuilder("asd-123-muumi"); 
    assertEquals("From: FlairImage line: 163", 0, separateNumber(testi,'-',totuus)); 
    assertEquals("From: FlairImage line: 164", "asd-123-muumi", testi.toString()); 
    assertEquals("From: FlairImage line: 165", false, totuus.get()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTakeNumberFromString224 */
  @Test
  public void testTakeNumberFromString224() {    // FlairImage: 224
    assertEquals("From: FlairImage line: 225", 123, takeNumberFromString("123")); 
    assertEquals("From: FlairImage line: 226", 0, takeNumberFromString("123a")); 
    assertEquals("From: FlairImage line: 227", -123, takeNumberFromString("-123")); 
    assertEquals("From: FlairImage line: 228", 0, takeNumberFromString("--123")); 
    assertEquals("From: FlairImage line: 229", 0, takeNumberFromString("pz4")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testShorten247 */
  @Test
  public void testShorten247() {    // FlairImage: 247
    assertEquals("From: FlairImage line: 248", "", shorten("asd.asd",7)); 
    assertEquals("From: FlairImage line: 249", "C:/Users/", shorten("C:/Users/asd.asd",7)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTakeExtensionAway264 */
  @Test
  public void testTakeExtensionAway264() {    // FlairImage: 264
    assertEquals("From: FlairImage line: 265", "asd", takeExtensionAway("asd.asd")); 
    assertEquals("From: FlairImage line: 266", "asd", takeExtensionAway("asd.a")); 
    assertEquals("From: FlairImage line: 267", "asd", takeExtensionAway("asd.")); 
    assertEquals("From: FlairImage line: 268", "asd", takeExtensionAway("asd")); 
    assertEquals("From: FlairImage line: 269", "", takeExtensionAway(".asd")); 
    assertEquals("From: FlairImage line: 270", "", takeExtensionAway(".")); 
    assertEquals("From: FlairImage line: 271", "asd.asd", takeExtensionAway("asd.asd.asd")); 
    assertEquals("From: FlairImage line: 272", "merkki.jono", takeExtensionAway("merkki.jono.png")); 
    assertEquals("From: FlairImage line: 273", "mer.kki.jono", takeExtensionAway("mer.kki.jono.png")); 
  } // Generated by ComTest END
}